
[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "v8.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/inwinstack/operator-kit"
  branch = "v1.11.0"

[[constraint]]
  name = "github.com/inwinstack/blended"
  version = "v0.6.0"

[prune]
  go-tests = true
  unused-packages = true
