
required = ["k8s.io/code-generator/cmd/client-gen"]

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "=v1.11.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "v8.0.0"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.11.0"

[prune]
  go-tests = true
